# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""

from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    MaxSigmoidAttnBlock,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    TorchVision,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    Index,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import (
    OBB,
    OBB26,
    Classify,
    Detect,
    LRPCHead,
    Pose,
    Pose26,
    RTDETRDecoder,
    Segment,
    Segment26,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    YOLOESegment26,
    v10Detect,
)
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
from .biformer import (
    BiFormerBlock,
    BiFormerNeck,
)
from .haar import (
    HaarDownsample,
    HaarDownsample2d,
)
from .spd import (
    SPDConv,
    SPDConv2d,
)
from .snake import (
    DSConv,
    DSConv2d,
    SnakeConv,
)
from .polarity import (
    PolarityInteractionModule,
    DualStreamPolarityFusion,
    PolarityFusion,
)
from .frequency import (
    GlobalFrequencyFilter,
    FrequencyYOLOBlock,
    FFTBlock,
)
from .lateral import (
    LateralInhibitionModule,
    LateralInhibitionBlock,
    LIM,
    LateralInhibition,
)
from .graph import (
    GraphReasoningModule,
    GraphYOLOBlock,
    GCNBlock,
)
from .connectivity import (
    ConnectivityAwareModule,
    ConnectivityBlock,
    ConnectivityAwareBlock,
)
from .vmamba import (
    VSSBlock,
    C2fVSS,
    C2fVSSBlock,
)
from .dcnv4 import (
    DCNv4,
    DCNv4Conv,
    DCNv4Block,
    DCNv4Conv2d,
)
from .seam import (
    SEAM,
    SEAMBlock,
    CSMM,
    MultiScaleDWSepConv,
)

__all__ = (
    "AIFI",
    "C1",
    "C2",
    "C2PSA",
    "C3",
    "C3TR",
    "CBAM",
    "CIB",
    "DFL",
    "ELAN1",
    "MLP",
    "OBB",
    "OBB26",
    "PSA",
    "SPP",
    "SPPELAN",
    "SPPF",
    "A2C2f",
    "AConv",
    "ADown",
    "Attention",
    "BNContrastiveHead",
    "Bottleneck",
    "BottleneckCSP",
    "C2f",
    "C2fAttn",
    "C2fCIB",
    "C2fPSA",
    "C3Ghost",
    "C3k2",
    "C3x",
    "CBFuse",
    "CBLinear",
    "ChannelAttention",
    "Classify",
    "Concat",
    "ContrastiveHead",
    "Conv",
    "Conv2",
    "ConvTranspose",
    "DWConv",
    "DWConvTranspose2d",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "Detect",
    "Focus",
    "GhostBottleneck",
    "GhostConv",
    "HGBlock",
    "HGStem",
    "ImagePoolingAttn",
    "Index",
    "LRPCHead",
    "LayerNorm2d",
    "LightConv",
    "MLPBlock",
    "MSDeformAttn",
    "MaxSigmoidAttnBlock",
    "Pose",
    "Pose26",
    "Proto",
    "RTDETRDecoder",
    "RepC3",
    "RepConv",
    "RepNCSPELAN4",
    "RepVGGDW",
    "ResNetLayer",
    "SCDown",
    "Segment",
    "Segment26",
    "SpatialAttention",
    "TorchVision",
    "TransformerBlock",
    "TransformerEncoderLayer",
    "TransformerLayer",
    "WorldDetect",
    "YOLOEDetect",
    "YOLOESegment",
    "YOLOESegment26",
    "v10Detect",
    "BiFormerBlock",
    "BiFormerNeck",
    "HaarDownsample",
    "HaarDownsample2d",
    "SPDConv",
    "SPDConv2d",
    "DSConv",
    "DSConv2d",
    "SnakeConv",
    "PolarityInteractionModule",
    "DualStreamPolarityFusion",
    "PolarityFusion",
    "GlobalFrequencyFilter",
    "FrequencyYOLOBlock",
    "FFTBlock",
    "LateralInhibitionModule",
    "LateralInhibitionBlock",
    "LIM",
    "LateralInhibition",
    "GraphReasoningModule",
    "GraphYOLOBlock",
    "GCNBlock",
    "ConnectivityAwareModule",
    "ConnectivityBlock",
    "ConnectivityAwareBlock",
    "VSSBlock",
    "C2fVSS",
    "C2fVSSBlock",
    "DCNv4",
    "DCNv4Conv",
    "DCNv4Block",
    "DCNv4Conv2d",
    "SEAM",
    "SEAMBlock",
    "CSMM",
    "MultiScaleDWSepConv",
)
